### ISSUE TITLE
Wrong calculation of 7% chance for double artifacts

### ISSUE THREAD

**Issue by Cronkhinator** [grumd/genshin-artifact-farm-calculator#3]
I am currently writing my own artifact sim with probabilities in preparation for my math and computer science finals and happened to stumble across your project. I checked the files and noticed that you calculate the chance for getting the desired artifact in one run (20 resin) the following way:
`chance = 1 - (1- chance) * (1 - 0.07 * chance)`
This confused me, as I first calculated the chance manually using `chance = chance * 1.07` and got a different result than you, so I ran a simulation to confirm the matter:
I created 100 million random artifacts with a 7% chance to create two at once and logged the amount of Flowers I got: 21400206
This proves that the chance for getting an artifact with chance c in one run (20 resin) with a chance of 7% for double artifacts is indeed `chance = chance * 1.07` instead of the formula you used.

This new formula can also be proven the following way:
`0.93 * chance + 0.07 * (2*chance*(1-chance)+2*(chance)²)`
- 93% chance to get 1 artifact (`0.93*chance`)
- 7% chance to get 2 artifacts (`0.07*...`)
-> getting *at least* one desired artifact from the drops: `2 * chance * (1-chance) + 2 * chance²`
Simplifying this formula leads to `chance = chance * 1.07` and calculates a probability of 21.4% for the aforementioned example (with chance = 0.2)

**Comment by grumd** [comment]
I have used `* 1.07` originally, but then changed it.

https://www.reddit.com/r/Genshin_Impact/comments/p9mdgk/comment/ha0z1a2/?utm_source=share&utm_medium=web2x&context=3

Here's the comment that convinced me to use a different formula.

Let me know if it convinces you too, or if you can disprove it.

**Comment by Cronkhinator** [comment]
Thanks for your response. I did another calculation making use of tree diagrams and got the same formula that was suggested in the comment you linked. It turns out I had an error in my previous calculation where I used `... +2*(chance)²)` while it should have been `...+chance²`. Simplifying that formula will then also lead to the one mentioned in the comment.
However, I also ran an artifact simulation many times over and over again: (Java)
`private static void simulateArtifacts() {
        List<String> ArtifactTypes = List.of("Flower", "Plume", "Sands", "Goblet", "Circlet");
        String s1;
        String s2;
        int numOfDesiredArtifacts = 0;
        int runs = 100000000;
        for (int i = 0; i <= runs; i++) {
            s1 = ArtifactTypes.get(Constants.randInt(0, ArtifactTypes.size() - 1));
            if (Math.random() <= 0.07) {
                s2 = ArtifactTypes.get(Constants.randInt(0, ArtifactTypes.size() - 1));
                if (s2.equals("Flower")) numOfDesiredArtifacts++;
            }
            if (s1.equals("Flower")) numOfDesiredArtifacts++;
        }
        double p = (double) numOfDesiredArtifacts / (double) runs;
        System.out.println(p);
    }`
Running this simulation returns a chance of 21.4% of receiving a Flower, which matches a base probability of 1.07.
Probability is confusing, I don't get this

**Comment by Cronkhinator** [comment]
Alright I did some more testing and I think I figured it out.
chance * 1.07 is the amount of desired artifacts you will get per run, while the suggested formula returns the chance of getting at least one desired artifact per run.
Sorry about the confusion, you may close this thread now.
