### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by EffortlessFury** [grumd/genshin-artifact-farm-calculator#4]
Hi, I'm looking into creating an application that utilizes the probabilities of given artifact rolls, and stumbled upon this handy tool. It would be awesome if I were able to reuse some of your logic but I noticed that this repo has no license. Are you interested in allowing for such modification/reuse?

**Comment by EffortlessFury** [comment]
idk why I didn't check but I see that someone already asked. I suppose this is just a ping to actually add one, then. XD

**Comment by grumd** [comment]
This reminds me that I should add Dendro DMG Bonus. I might add a LICENSE file too, if I get some time to work on this again

**Comment by EffortlessFury** [comment]
I actually ended up adding Dendro, I'll submit a PR soonish.

**Comment by grumd** [comment]
@EffortlessFury Added a dendro cup and a license

**Comment by EffortlessFury** [comment]
Ahhh, sorry, I forgot to submit that PR. Sorry about that.
