### ISSUE TITLE
Total chances got scuffed

### ISSUE THREAD

**Issue by Pocq** [grumd/genshin-artifact-farm-calculator#5]
Probably since the addition of dendro.
To test it, simply use "Flower of life" and run, it should give flat 10% (or 20% for combined).
Elemental goblets display 0.535% (or 1.07%) which are the only correct values, every other % should have been the same except ATK%, DEF%, HP% for goblets.

Minor things:
The UI is written in English but the X-Axis is displayed in local language: 
![image](https://user-images.githubusercontent.com/105499051/223831173-9a5cfb38-3858-4a29-a32f-b73ac37c9575.png)

Would it be possible to add custom resin usage per day? In case people use fragile resins/refills or only allocate a lower resin amount per day to artifacts. Hovering gives you the resin value to manually divide but this would be more convenient.

**Comment by grumd** [comment]
@Pocq It shouldn't be 10% because there's a 7% chance you'll get **TWO** artifacts from 20 resin.

Yeah you're right, local language doesn't look good when everything else is English, I'll make that text English as well.

Added an input for resin per day
